path: F:/GEFDNet/datasets/WGISD
train: # train images (relative to 'path')
  - train/images

val: # val images (relative to 'path') 
  - val/images

test: # test images (optional)
  - test/images

# Classes
names:
  0: label